import type { MappedArg, MappedFlag, MappedOperation, MappedResource } from './join';

let flagTypeName: Record<MappedFlag['type'], string> = {
  string: 'resourcecmd.FlagString',
  bool: 'resourcecmd.FlagBool',
  int: 'resourcecmd.FlagInt',
  float: 'resourcecmd.FlagFloat',
  'string-slice': 'resourcecmd.FlagStringSlice',
  json: 'resourcecmd.FlagJSON',
  'json-file': 'resourcecmd.FlagJSONFile'
};

export let emitCatalogGo = (resources: MappedResource[]) => {
  let body = resources.map(resource => emitResource(resource, 1)).join(',\n');

  return `// Code generated by oss/cli/generator. DO NOT EDIT.

package admin

import "github.com/metorial/cli/internal/resourcecmd"

func Catalog() []resourcecmd.ResourceSpec {
	return []resourcecmd.ResourceSpec{
${body},
	}
}
`;
};

let emitResource = (resource: MappedResource, indent: number): string => {
  let pad = '\t'.repeat(indent);
  let inner = '\t'.repeat(indent + 1);
  let lines = [
    `${pad}{`,
    `${inner}Plural:   ${goString(resource.plural)},`,
    `${inner}Singular: ${goString(resource.singular)},`,
    `${inner}Short:    ${goString(resource.short)},`,
    `${inner}Long:     ${goString(resource.long)},`
  ];

  if (resource.aliases.length) {
    lines.push(`${inner}Aliases:  []string{${resource.aliases.map(goString).join(', ')}},`);
  }

  lines.push(`${inner}Operations: []resourcecmd.OperationSpec{`);
  if (resource.operations.length) {
    lines.push(resource.operations.map(operation => emitOperation(operation, indent + 2)).join(',\n') + ',');
  }
  lines.push(`${inner}},`);

  if (resource.shortcuts.length) {
    lines.push(`${inner}Shortcuts: []resourcecmd.ShortcutSpec{`);
    for (let shortcut of resource.shortcuts) {
      lines.push(
        `${inner}\t{Path: []string{${shortcut.path.map(goString).join(', ')}}, Method: ${goString(shortcut.method)}},`
      );
    }
    lines.push(`${inner}},`);
  }

  if (resource.children.length) {
    lines.push(`${inner}Children: []resourcecmd.ResourceSpec{`);
    lines.push(resource.children.map(child => emitResource(child, indent + 2)).join(',\n') + ',');
    lines.push(`${inner}},`);
  }

  lines.push(`${pad}}`);
  return lines.join('\n');
};

let emitOperation = (operation: MappedOperation, indent: number) => {
  let pad = '\t'.repeat(indent);
  let inner = '\t'.repeat(indent + 1);
  let lines = [
    `${pad}{`,
    `${inner}Name:       ${goString(operation.name)},`,
    `${inner}Method:     ${goString(operation.method)},`,
    `${inner}Path:       ${goString(operation.path)},`,
    `${inner}Short:      ${goString(operation.short)},`,
    `${inner}Long:       ${goString(operation.long)},`,
    `${inner}SDKMapping: ${goString(operation.sdkMapping)},`
  ];

  if (operation.args.length) {
    lines.push(`${inner}Args: []resourcecmd.ArgumentSpec{`);
    for (let arg of operation.args) {
      lines.push(`${inner}\t${emitArg(arg)},`);
    }
    lines.push(`${inner}},`);
  }

  if (operation.flags.length) {
    lines.push(`${inner}Flags: []resourcecmd.FlagSpec{`);
    for (let flag of operation.flags) {
      lines.push(`${inner}\t${emitFlag(flag)},`);
    }
    lines.push(`${inner}},`);
  }

  lines.push(`${pad}}`);
  return lines.join('\n');
};

let emitArg = (arg: MappedArg) =>
  `{Name: ${goString(arg.name)}, Target: ${goString(arg.target)}, Required: ${arg.required}, Description: ${goString(arg.description)}}`;

let emitFlag = (flag: MappedFlag) =>
  `{Name: ${goString(flag.name)}, Type: ${flagTypeName[flag.type]}, Target: ${goString(flag.target)}, Usage: ${goString(flag.usage)}, Required: ${flag.required}, Repeated: ${flag.repeated}}`;

let goString = (value: string) => JSON.stringify(value || '');
