package resourcecmd

func DeploymentsResource() ResourceSpec {
	return ResourceSpec{
		Plural:     "deployments",
		Singular:   "deployment",
		Short:      "Manage provider deployments",
		Long:       "Create and manage provider deployments.",
		PathPlural: "provider-deployments",
		Operations: []OperationSpec{
			{
				Name:  OperationList,
				Short: "List deployments",
				Long:  "List deployments for the selected instance. When provided, the optional search argument filters by name or description.",
				Args:  []ArgumentSpec{arg("search", "params.Search", "Search deployments by name or description.", false)},
				Flags: append(
					paginationFlags("deployments"),
					stringSliceFlag("id", "params.Id", "Filter by deployment ID"),
					stringSliceFlag("provider-id", "params.ProviderId", "Filter by provider ID"),
					stringSliceFlag("provider-version-id", "params.ProviderVersionId", "Filter by provider version ID"),
					stringSliceFlag("status", "params.Status", "Filter by deployment status"),
				),
				Examples: []string{"metorial deployments list github"},
			},
			{
				Name:     OperationGet,
				Short:    "Get a deployment",
				Long:     "Get a single deployment by ID.",
				Args:     []ArgumentSpec{arg("deployment-id", "", "Deployment ID. Find one with `metorial deployments list`.", true)},
				Examples: []string{"metorial deployments get dep_123"},
			},
			{
				Name:  OperationCreate,
				Short: "Create a deployment",
				Long:  "Create a deployment from an existing provider.",
				Args: []ArgumentSpec{
					arg("provider-id", "body.ProviderId", "Provider to deploy. Find one with `metorial providers list`.", true),
					arg("name", "body.Name", "Display name for the deployment.", true),
				},
				Flags: []FlagSpec{
					stringFlag("description", "body.Description", "Optional description", false),
					stringFlag("locked-provider-version-id", "body.LockedProviderVersionId", "Pinned provider version", false),
					stringFlag("provider-config-id", "body.ProviderConfigId", "Existing provider config ID", false),
					jsonFlag("provider-config", "body.ProviderConfig", "Inline JSON object for provider config"),
					jsonFileFlag("provider-config-file", "body.ProviderConfig", "Read provider config JSON from a file"),
					jsonFlag("metadata", "body.Metadata", "Inline JSON object for metadata"),
					jsonFileFlag("metadata-file", "body.Metadata", "Read metadata JSON from a file"),
					jsonFlag("tool-filters", "body.ToolFilters", "Inline JSON value for tool filters"),
					jsonFileFlag("tool-filters-file", "body.ToolFilters", "Read tool filters JSON from a file"),
				},
				Examples: []string{
					`metorial deployments create prv_123 "Production deployment"`,
				},
				SeeAlso: []string{"metorial providers list", "metorial configs list"},
			},
			{
				Name:  OperationUpdate,
				Short: "Update a deployment",
				Long:  "Update mutable fields on a deployment.",
				Args:  []ArgumentSpec{arg("deployment-id", "", "Deployment ID. Find one with `metorial deployments list`.", true)},
				Flags: []FlagSpec{
					stringFlag("name", "body.Name", "Updated display name", false),
					stringFlag("description", "body.Description", "Updated description", false),
					jsonFlag("metadata", "body.Metadata", "Inline JSON object for metadata"),
					jsonFileFlag("metadata-file", "body.Metadata", "Read metadata JSON from a file"),
					jsonFlag("tool-filters", "body.ToolFilters", "Inline JSON value for tool filters"),
					jsonFileFlag("tool-filters-file", "body.ToolFilters", "Read tool filters JSON from a file"),
				},
				Examples: []string{"metorial deployments update dep_123 --description \"Updated description\""},
			},
		},
	}
}

func ConfigsResource() ResourceSpec {
	return ResourceSpec{
		Plural:     "configs",
		Singular:   "config",
		Short:      "Manage provider configs",
		Long:       "Create and manage provider configuration objects.",
		PathPlural: "provider-configs",
		Operations: []OperationSpec{
			{
				Name:  OperationList,
				Short: "List configs",
				Long:  "List provider configs for the selected instance. When provided, the optional search argument filters by name or description.",
				Args:  []ArgumentSpec{arg("search", "params.Search", "Search configs by name or description.", false)},
				Flags: append(paginationFlags("configs"),
					stringSliceFlag("status", "params.Status", "Filter by config status"),
					stringSliceFlag("id", "params.Id", "Filter by config ID"),
					stringSliceFlag("provider-id", "params.ProviderId", "Filter by provider ID"),
					stringSliceFlag("provider-specification-id", "params.ProviderSpecificationId", "Filter by provider specification ID"),
					stringSliceFlag("provider-deployment-id", "params.ProviderDeploymentId", "Filter by provider deployment ID"),
					stringSliceFlag("provider-config-vault-id", "params.ProviderConfigVaultId", "Filter by config vault ID"),
				),
				Examples: []string{"metorial configs list"},
			},
			{
				Name:     OperationGet,
				Short:    "Get a config",
				Long:     "Get a single provider config by ID.",
				Args:     []ArgumentSpec{arg("config-id", "", "Config ID. Find one with `metorial configs list`.", true)},
				Examples: []string{"metorial configs get cfg_123"},
			},
			{
				Name:  OperationCreate,
				Short: "Create a config",
				Long:  "Create a provider config for a provider, optionally tied to a deployment.",
				Args:  []ArgumentSpec{arg("provider-id", "body.ProviderId", "Provider ID. Find one with `metorial providers list`.", true)},
				Flags: []FlagSpec{
					stringFlag("provider-deployment-id", "body.ProviderDeploymentId", "Optional provider deployment ID", false),
					stringFlag("name", "body.Name", "Optional display name", false),
					stringFlag("description", "body.Description", "Optional description", false),
					jsonFlag("value", "body.Value", "Inline JSON object for config values"),
					jsonFileFlag("value-file", "body.Value", "Read config values JSON from a file"),
					stringFlag("provider-config-vault-id", "body.ProviderConfigVaultId", "Config vault ID to use as a template", false),
					jsonFlag("metadata", "body.Metadata", "Inline JSON object for metadata"),
					jsonFileFlag("metadata-file", "body.Metadata", "Read metadata JSON from a file"),
					jsonFlag("tool-filters", "body.ToolFilters", "Inline JSON value for tool filters"),
					jsonFileFlag("tool-filters-file", "body.ToolFilters", "Read tool filters JSON from a file"),
				},
				Examples: []string{"metorial configs create prv_123 --value-file config.json"},
				SeeAlso:  []string{"metorial providers list", "metorial deployments list"},
			},
			{
				Name:  OperationUpdate,
				Short: "Update a config",
				Long:  "Update mutable fields on a provider config.",
				Args:  []ArgumentSpec{arg("config-id", "", "Config ID. Find one with `metorial configs list`.", true)},
				Flags: []FlagSpec{
					stringFlag("name", "body.Name", "Updated display name", false),
					stringFlag("description", "body.Description", "Updated description", false),
					jsonFlag("metadata", "body.Metadata", "Inline JSON object for metadata"),
					jsonFileFlag("metadata-file", "body.Metadata", "Read metadata JSON from a file"),
					jsonFlag("tool-filters", "body.ToolFilters", "Inline JSON value for tool filters"),
					jsonFileFlag("tool-filters-file", "body.ToolFilters", "Read tool filters JSON from a file"),
				},
				Examples: []string{"metorial configs update cfg_123 --description \"Updated description\""},
			},
		},
	}
}

func AuthConfigsResource() ResourceSpec {
	return ResourceSpec{
		Plural:     "auth-configs",
		Singular:   "auth-config",
		Short:      "Manage provider auth configs",
		Long:       "Create and manage provider authentication configs.",
		PathPlural: "provider-auth-configs",
		Operations: []OperationSpec{
			{
				Name:  OperationList,
				Short: "List auth configs",
				Long:  "List provider auth configs for the selected instance. When provided, the optional search argument filters by name or description.",
				Args:  []ArgumentSpec{arg("search", "params.Search", "Search auth configs by name or description.", false)},
				Flags: append(paginationFlags("auth configs"),
					stringSliceFlag("status", "params.Status", "Filter by auth config status"),
					stringSliceFlag("id", "params.Id", "Filter by auth config ID"),
					stringSliceFlag("provider-id", "params.ProviderId", "Filter by provider ID"),
					stringSliceFlag("provider-deployment-id", "params.ProviderDeploymentId", "Filter by provider deployment ID"),
					stringSliceFlag("provider-auth-credentials-id", "params.ProviderAuthCredentialsId", "Filter by provider auth credentials ID"),
					stringSliceFlag("provider-auth-method-id", "params.ProviderAuthMethodId", "Filter by provider auth method ID"),
				),
				Examples: []string{"metorial auth-configs list github"},
			},
			{
				Name:     OperationGet,
				Short:    "Get an auth config",
				Long:     "Get a single provider auth config by ID.",
				Args:     []ArgumentSpec{arg("auth-config-id", "", "Auth config ID. Find one with `metorial auth-configs list`.", true)},
				Examples: []string{"metorial auth-configs get acf_123"},
			},
			{
				Name:  OperationCreate,
				Short: "Create an auth config",
				Long:  "Create a provider auth config using a provider auth method and auth payload.",
				Args:  []ArgumentSpec{arg("provider-auth-method-id", "body.ProviderAuthMethodId", "Provider auth method ID.", true)},
				Flags: []FlagSpec{
					stringFlag("name", "body.Name", "Optional display name", false),
					stringFlag("description", "body.Description", "Optional description", false),
					stringFlag("provider-deployment-id", "body.ProviderDeploymentId", "Optional provider deployment ID", false),
					jsonFlag("value", "body.Value", "Inline JSON object for auth config values"),
					jsonFileFlag("value-file", "body.Value", "Read auth config values JSON from a file"),
					jsonFlag("metadata", "body.Metadata", "Inline JSON object for metadata"),
					jsonFileFlag("metadata-file", "body.Metadata", "Read metadata JSON from a file"),
					jsonFlag("tool-filters", "body.ToolFilters", "Inline JSON value for tool filters"),
					jsonFileFlag("tool-filters-file", "body.ToolFilters", "Read tool filters JSON from a file"),
				},
				Examples: []string{"metorial auth-configs create pam_123 --value-file auth.json"},
				SeeAlso:  []string{"metorial deployments list"},
			},
			{
				Name:  OperationUpdate,
				Short: "Update an auth config",
				Long:  "Update mutable fields on a provider auth config.",
				Args:  []ArgumentSpec{arg("auth-config-id", "", "Auth config ID. Find one with `metorial auth-configs list`.", true)},
				Flags: []FlagSpec{
					stringFlag("name", "body.Name", "Updated display name", false),
					stringFlag("description", "body.Description", "Updated description", false),
					jsonFlag("metadata", "body.Metadata", "Inline JSON object for metadata"),
					jsonFileFlag("metadata-file", "body.Metadata", "Read metadata JSON from a file"),
					jsonFlag("tool-filters", "body.ToolFilters", "Inline JSON value for tool filters"),
					jsonFileFlag("tool-filters-file", "body.ToolFilters", "Read tool filters JSON from a file"),
				},
				Examples: []string{"metorial auth-configs update acf_123 --description \"Updated description\""},
			},
		},
	}
}
